function data = importfile_coax(filename, dataLines)
%IMPORTFILE2 Import data from a text file
%  CONTROL = IMPORTFILE2(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  CONTROL = IMPORTFILE2(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  
%  See also READTABLE.
%
% Auto-generated by MATLAB on 23-Aug-2024 17:29:54

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "Model", "Controlmph", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["VarName1", "Model", "Controlmph", "VarName4", "VarName5", "VarName6", "VarName7", "VarName8"], "ThousandsSeparator", ",");

% Import the data
data = readtable(filename, opts);

%% Convert to output type
data = table2array(data);
end